name: "CI for can-priority-queue"
on: [push, pull_request]
jobs:
  run-munit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: can-priority-queue/test
    steps:
      - uses: actions/checkout@v2
      - run: make test
      - run : ./test
